<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MInvoice extends CI_Model
{

    public $table = 'invoice';
    public $id = 'id_invoice';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_union()
    {
        $res = $this->db->query("SELECT kode_pesanan from vendor union SELECT kode_pesanan from invoice")->result();
        return $res;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_invoice', $q);
        $this->db->like('kode_pesanan', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('jumlah_pembayaran', $q);
    $this->db->or_like('bukti_pembayaran', $q);
	$this->db->or_like('tanggal_pembayaran', $q);
	$this->db->or_like('status', $q);
    $this->db->or_like('jumlah_pembayaran_customer', $q);
    $this->db->or_like('bukti_pembayaran_customer', $q);
    $this->db->or_like('tanggal_pembayaran_customer', $q);
    $this->db->or_like('status_customer', $q);

	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->select('i.*,v.nama_client,v.alamat,v.kode_pesanan');
    $this->db->from('invoice i');
    $this->db->join('vendor v', 'v.kode_pesanan = i.kode_pesanan');


        $this->db->order_by('i.id_invoice', $this->order);
        $this->db->like('i.id_invoice', $q);
        $this->db->like('i.kode_pesanan', $q);
	$this->db->or_like('i.nama_client', $q);
	$this->db->or_like('i.alamat', $q);
	$this->db->or_like('i.jumlah_pembayaran', $q);
    $this->db->or_like('i.bukti_pembayaran', $q);
	$this->db->or_like('i.tanggal_pembayaran', $q);
	$this->db->or_like('i.status', $q);
    $this->db->or_like('i.jumlah_pembayaran_customer', $q);
    $this->db->or_like('i.bukti_pembayaran_customer', $q);
    $this->db->or_like('i.tanggal_pembayaran_customer', $q);
    $this->db->or_like('i.status_customer', $q);

	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MInvoice.php */
/* Location: ./application/models/MInvoice.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-08 11:45:43 */
/* http://harviacode.com */