<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MUser extends CI_Model
{

    public $table = 'user';
    public $id = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //checkuser
    // public function Checkuser($u,$p)
    // {
    //     // SELECT * FROM user WHERE username = '$username'
    //     $query = $this->db->get_where($this->table,
    //             array('username'=>$u,'password'=>$p)
    //             ); // cek username ada atau tidak
    //     // cek apakah ada atau tidak
    //     if($query->num_rows() > 0){
    //         return true;
    //     } else
    //     {
    //         return false;
    //     }
    // }

    public function Checkuser($u)
    {
        // SELECT * FROM user WHERE username = '$username'
        $query = $this->db->get_where($this->table,
                array('username'=>$u)
                ); // cek username ada atau tidak
        // cek apakah ada atau tidak
        if($query->num_rows() > 0){
            return true;
        } else
        {
            return false;
        }
    }

    public function cekStatus($u)
{
    $query = $this->db->get_where($this->table,array('username'=>$u, 'status'=>'approve'));
    if($query->num_rows() > 0) {
        return true;
    }
    else {
    return false;
    }
}

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get username
    function get_by_username($username)
    {
        $this->db->where('username',$username);
        return $this->db->get($this->table)->row();
    }
    
    //cek nama client
     function get_by_nama_client($nama_client)
     {
          $this->db->where('nama_client', $nama_client);
          return $this->db->get($this->table)->row();
     }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user', $q);
    $this->db->or_like('username', $q);
    $this->db->or_like('password', $q);
    $this->db->or_like('email', $q);
    $this->db->or_like('nama_lengkap', $q);
    $this->db->or_like('Alamat', $q);
    $this->db->or_like('hak_akses', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user', $q);
    $this->db->or_like('username', $q);
    $this->db->or_like('password', $q);
    $this->db->or_like('email', $q);
    $this->db->or_like('nama_lengkap', $q);
    $this->db->or_like('Alamat', $q);
    $this->db->or_like('hak_akses', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function CheckApprove()
    {
        $this->db->where('status','belum approve');
        return $this->db->get($this->table)->result();
    }

}

/* End of file MUser.php */
/* Location: ./application/models/MUser.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-20 04:53:52 */
/* http://harviacode.com */