<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MVendor extends CI_Model
{

    public $table = 'vendor';
    public $id = 'id_vendor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //  function get_all_invoiced()
    // {
    //     $this->db->from("vendor v");
    //     $this->db->join("invoice i","v.kode_pesanan = i.kode_pesanan");
    //    $this->db->where('i.kode_pesanan is NULL', NULL, FALSE);
    //    $this->db->group_by("i.kode_pesanan");
    //     return $this->db->get()->result();
    // }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_vendor', $q);
    $this->db->like('kode_pesanan', $q);
	$this->db->or_like('nama_vendor', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('email', $q);
    $this->db->or_like('jenis_transportasi', $q);
    $this->db->or_like('jumlah_pembayaran', $q);
    $this->db->or_like('tanggal_pesanan', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_vendor', $q);
    $this->db->like('kode_pesanan', $q);
	$this->db->or_like('nama_vendor', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('email', $q);
    $this->db->or_like('jenis_transportasi', $q);
    $this->db->or_like('jumlah_pembayaran', $q);
    $this->db->or_like('tanggal_pesanan', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    // function insert($data)
    // {
    //     $this->db->insert($this->table, $data);
    // }    

  function insert($data){
   $this->db->insert($this->table, $data);
   $insert_id = $this->db->insert_id();

   return $insert_id;
}
    // update data
    // function update($id, $data)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->update($this->table, $data);
    // }
// Di dalam model MVendor.php

public function update($id, $data)
{
    // Menghapus kolom 'kode_pesanan' dari data yang akan di-update
    unset($data['kode_pesanan']);

    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
}


// public function update($data)
// {
//     // Ambil ID vendor dari $data
//     $id_vendor = $data['id_vendor'];
//     $this->db->update($this->table, $data);


    
// }

//  function update($data){
//    $this->db->update($this->table, $data);
//    $insert_id = $this->db->update_id();

//    return $insert_id;
// }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MVendor.php */
/* Location: ./application/models/MVendor.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-06 12:47:43 */
/* http://harviacode.com */