<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id_client';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
 //checkuser
    public function Checkuser($u, $p)
    {
        // SELECT * FROM user WHERE username = '$username' AND password = '$password'
        $query = $this->db->get_where($this->table,
                array('username'=>$u,
                      'password'=>$p)
                );
        // cek apakah ada atau tidak
        if($query->num_rows() > 0){
            return true;
        } else
        {
            return false;
        }
    }

    public function cekStatus($u)
{
    $query = $this->db->get_where($this->table,array('username'=>$u, 'status'=>'approve'));
    if($query->num_rows() > 0) {
        return true;
    }
    else {
    return false;
    }
}
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    //cek nama
     function get_by_nama_client($nama_client)
     {
          $this->db->where('nama_client', $nama_client);
          return $this->db->get($this->table)->row();
     }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_client', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('hak_akses', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_client', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('hak_akses', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function CheckApprove()
    {
        $this->db->where('status','belum approve');
        return $this->db->get($this->table)->result();
    }


}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-06 11:33:01 */
/* http://harviacode.com */